# Generated by Django 2.1.2 on 2018-10-24 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('statement', models.TextField(verbose_name='enunciado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem')),
                ('alternative_one', models.CharField(max_length=255, verbose_name='alternativa 1')),
                ('alternative_two', models.CharField(max_length=255, verbose_name='alternativa 2')),
                ('alternative_three', models.CharField(max_length=255, verbose_name='alternativa 3')),
                ('alternative_four', models.CharField(max_length=255, verbose_name='alternativa 4')),
                ('correct_alternative', models.CharField(max_length=255, verbose_name='alternativa correta')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='banco.Matter', verbose_name='materia')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
            options={
                'verbose_name': 'questao',
                'verbose_name_plural': 'questoes',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matte', to='banco.Matter', verbose_name='materia')),
                ('questions', models.ManyToManyField(related_name='questions', to='banco.Question', verbose_name='questoes')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
            options={
                'verbose_name': 'prova',
                'verbose_name_plural': 'provas',
            },
        ),
    ]
